export ABS_BUILD_DEVICES=pxa1936dkb_tz:pxa1936dkb
export ABS_BOARD=concord
export ABS_DROID_BRANCH=lmr1
export ABS_SOC=pxa1936
export PLATFORM_ANDROID_VARIANT=userdebug
export ABS_BUILDHOST_DEF=buildhost6.def
#export ABS_MANIFEST_BRANCH="$ABS_BOARD-$ABS_DROID_BRANCH"
export ABS_UNIQUE_MANIFEST_BRANCH=1

