export ABS_BOARD=concord
export ABS_DROID_BRANCH=kk4.4
export ABS_SOC=eden
export PLATFORM_ANDROID_VARIANT=userdebug
#export ABS_MANIFEST_BRANCH="$ABS_BOARD-$ABS_DROID_BRANCH"
export ABS_UNIQUE_MANIFEST_BRANCH=1

