export ABS_BOARD=concord
export ABS_DROID_BRANCH=pdk5.0
export ABS_SOC=pxa1928
export PLATFORM_ANDROID_VARIANT=eng
export ABS_BUILDHOST_DEF=buildhost5.def
#export ABS_MANIFEST_BRANCH="$ABS_BOARD-$ABS_DROID_BRANCH"
export ABS_UNIQUE_MANIFEST_BRANCH=1

