export ABS_BOARD=concord
export ABS_DROID_BRANCH=lp5.1
export ABS_SOC=pxa1928
#export PLATFORM_ANDROID_VARIANT=userdebug
#export ABS_MANIFEST_BRANCH="$ABS_BOARD-$ABS_DROID_BRANCH"
export ABS_UNIQUE_MANIFEST_BRANCH=1

